pool:
  vmImage: 'ubuntu-latest'

steps:

# Updating the python version available on the linux agent
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

# Updating pip to latest
- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

# Updating to latest Azure CLI version.
- script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
  displayName: 'upgrade azure cli'


- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get -qq update
  displayName: 'Add GCC Repository'
  continueOnError: false

- script: |
    sudo apt-get install -y build-essential software-properties-common
    sudo apt-get install -y gcc-10
    sudo apt-get install -y g++-10 mingw-w64 libgmp-dev bison
    sudo apt-get install -y libmpfr-dev libmpc-dev
    sudo apt-get install -y byacc texinfo
    sudo apt-get install -y zip gzip tar
  displayName: 'Install Required Packages'
  continueOnError: false

- bash: |
    cd $BUILD_SOURCESDIRECTORY
    touch "CHANGELOG.txt"
    git log --oneline --decorate > CHANGELOG.txt
  displayName: 'Create Changelog'
  continueOnError: false

- script: |
    cd $BUILD_SOURCESDIRECTORY/scripts/build/linux64
    bash ./build-linux64-toolchain.sh
    tar -czf ../gcc-toolchain-mips64-linux64.tar.gz *
  displayName: 'Build linux64 Project'
  continueOnError: false

- bash: |
    mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/linux64/
    mv "$BUILD_SOURCESDIRECTORY/scripts/build/gcc-toolchain-mips64-linux64.tar.gz" "$BUILD_ARTIFACTSTAGINGDIRECTORY/linux64/"
  displayName: 'Move linux Artifacts to Staging Directory'
  continueOnError: false

# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: Publish linux Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'binaries' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    parallel: true # Optional
    #parallelCount: # Optional


- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'MsdnAzureServiceRole'
    scriptLocation: inlineScript
    inlineScript: 'az storage blob upload --account-name n64tools -f $(Build.ArtifactStagingDirectory)/linux64/gcc-toolchain-mips64-linux64.tar.gz -c binaries -n N64-tools/mips64-gcc-toolchain/$(Build.SourceBranchName)/latest/gcc-toolchain-mips64-linux64.tar.gz'
  displayName: Upload linux binary to blob storage
  

- script: |
    cd $BUILD_SOURCESDIRECTORY/scripts/build/win64
    bash ./build-win64-toolchain.sh
    zip -rq ../gcc-toolchain-mips64-win64.zip *
  displayName: 'Build win64 Project'
  continueOnError: false

- bash: |
    mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/win64/
    mv "$BUILD_SOURCESDIRECTORY/scripts/build/gcc-toolchain-mips64-win64.zip" "$BUILD_ARTIFACTSTAGINGDIRECTORY/win64/"
  displayName: 'Move windows Artifacts to Staging Directory'
  continueOnError: false

# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: Publish windows Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'binaries' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    parallel: true # Optional
    #parallelCount: # Optional
      
- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'MsdnAzureServiceRole'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name n64tools -f $(Build.ArtifactStagingDirectory)/win64/gcc-toolchain-mips64-win64.zip -c binaries -n N64-tools/mips64-gcc-toolchain/$(Build.SourceBranchName)/latest/gcc-toolchain-mips64-win64.zip'
  displayName: Upload windows binary to blob storage
  
