pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    echo Getting the latest GCC version:
    sudo add-apt-repository ppa:jonathonf/gcc -y
    sudo apt-get -qq update
  displayName: 'Add GCC 8.1 Repository'
  continueOnError: false

- script: |
    sudo add-apt-repository ppa:jonathonf/gcc -y
    sudo apt-get -qq update
  displayName: 'Update Distro'
  continueOnError: false

- script: |
    sudo apt-get install -y build-essential software-properties-common
    sudo apt-get install -y gcc-8
    sudo apt-get install -y mingw-w64 libgmp-dev bison
    sudo apt-get install -y libmpfr-dev libmpc-dev
    sudo apt-get install -y byacc texinfo
    sudo apt-get install -y zip gzip tar
  displayName: 'Install Required Packages'
  continueOnError: false

- bash: |
    cd $BUILD_SOURCESDIRECTORY
    touch "CHANGELOG.txt"
    git log --oneline --decorate > CHANGELOG.txt
  displayName: 'Create Changelog'

- script: |
    bash ./build.sh
  displayName: 'Build Project'
  continueOnError: false

# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/scripts/build/' 
    artifactName: 'gcc-toolchain-mips64-linux64' 
    publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    parallel: true # Optional
    #parallelCount: # Optional
